(function(){
const WW=40,WH=26,VW=24,VH=16,T=28;
const AS={base:'assets/tile-base.svg',crate:'assets/tile-crate.svg',tree:'assets/tile-tree.svg',grove:'assets/tile-grove.svg',food:'assets/tile-food.svg',water:'assets/tile-water.svg',scrap:'assets/tile-scrap.svg',medical:'assets/tile-medical.svg',weapon:'assets/tile-weapon.svg',event:'assets/tile-event.svg',trader:'assets/tile-trader.svg',enemy:'assets/tile-enemy.svg',rare:'assets/tile-rare.svg',boss:'assets/tile-boss.svg',empty:'assets/tile-empty.svg'};
const PAL={city:{a:'#34363a',b:'#2c2f33',w:'#17191c',l:'#565a60',f:'#111317'},sewer:{a:'#263a31',b:'#1f3029',w:'#0d1814',l:'#426a55',f:'#0c1512'},factory:{a:'#3b302a',b:'#302621',w:'#171311',l:'#74513d',f:'#15110f'},farmland:{a:'#3d4028',b:'#33351f',w:'#171b12',l:'#626a37',f:'#11140e'}};
const imgs=new Map();let raf=0,last=performance.now();const oldGen=generateMap,oldMove=moveDog;
function img(src){if(!imgs.has(src)){const i=new Image();i.src=src;imgs.set(src,i);}return imgs.get(src);}
function W(){if(!state.world)state.world={};return state.world;}
function K(x,y){return x+','+y;}function inside(x,y){return x>=0&&y>=0&&x<WW&&y<WH;}function floor(w,x,y){return inside(x,y)&&w.tiles[y][x]===1;}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function rng(seed){let v=2166136261;for(const c of String(seed)){v^=c.charCodeAt(0);v=Math.imul(v,16777619);}return()=>{v+=0x6D2B79F5;let t=v;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function carve(w,x,y){if(inside(x,y))w.tiles[y][x]=1;}
function room(w,cx,cy,rw,rh){const l=clamp(Math.round(cx-rw/2),1,WW-rw-2),t=clamp(Math.round(cy-rh/2),1,WH-rh-2);for(let y=t;y<t+rh;y++)for(let x=l;x<l+rw;x++)carve(w,x,y);return{left:l,top:t,w:rw,h:rh,cx:l+Math.floor(rw/2),cy:t+Math.floor(rh/2)};}
function corridor(w,a,b,r){let x=a.x,y=a.y;const sx=()=>{while(x!==b.x){x+=Math.sign(b.x-x);carve(w,x,y);carve(w,x,y+1);}},sy=()=>{while(y!==b.y){y+=Math.sign(b.y-y);carve(w,x,y);carve(w,x+1,y);}};if(r()>.5){sx();sy();}else{sy();sx();}}
function roomCell(n){return{x:clamp(3+Math.round(n.gridX/12*(WW-7)),3,WW-4),y:clamp(3+Math.round(n.gridY/8*(WH-7)),3,WH-4)};}
function nearFloor(w,x,y){if(floor(w,x,y))return{x,y};for(let q=1;q<8;q++)for(let yy=y-q;yy<=y+q;yy++)for(let xx=x-q;xx<=x+q;xx++)if(floor(w,xx,yy))return{x:xx,y:yy};return{x:2,y:2};}
function randomFloor(w,r,away){for(let n=0;n<500;n++){const x=1+Math.floor(r()*(WW-2)),y=1+Math.floor(r()*(WH-2));if(floor(w,x,y)&&(!away||Math.hypot(x-away.x,y-away.y)>5))return{x,y};}return nearFloor(w,2,2);}
function build(){const r=rng(state.mapSeed+'-world-v27'),w={width:WW,height:WH,tileSize:T,tiles:Array.from({length:WH},()=>Array(WW).fill(0)),rooms:[],props:[],enemies:[],dog:{x:2,y:2,path:[],targetProp:null,facing:1,moving:false},discovered:new Set(),searched:0,camera:{x:0,y:0},seed:state.mapSeed,ready:true};
state.map.forEach(n=>{const c=roomCell(n);w.rooms[n.id]={...room(w,c.x,c.y,n.critical?7:5,n.critical?5:4),nodeId:n.id};});
state.map.forEach(n=>n.links.forEach(id=>{if(n.id<id&&w.rooms[id])corridor(w,{x:w.rooms[n.id].cx,y:w.rooms[n.id].cy},{x:w.rooms[id].cx,y:w.rooms[id].cy},r);}));
state.map.forEach(n=>{const c=w.rooms[n.id],p=nearFloor(w,c.cx+(r()>.5?1:-1),c.cy+(r()>.5?1:-1));w.props.push({id:'prop-'+n.id,roomId:n.id,type:n.type,x:p.x+.5,y:p.y+.5,searched:n.cleared,pulse:r()*Math.PI*2});});
const e=state.map.find(n=>n.role==='entrance')||state.map[0],s=w.rooms[e.id];w.dog.x=s.cx+.5;w.dog.y=s.cy+.5;w.camera.x=clamp(w.dog.x-VW/2,0,WW-VW);w.camera.y=clamp(w.dog.y-VH/2,0,WH-VH);reveal(w,w.dog.x,w.dog.y,5);state.world=w;sync(w);return w;}
function neigh(w,x,y){return[[1,0],[-1,0],[0,1],[0,-1]].map(([a,b])=>({x:x+a,y:y+b})).filter(c=>floor(w,c.x,c.y));}
function path(w,start,end){const a={x:Math.floor(start.x),y:Math.floor(start.y)},b=nearFloor(w,Math.floor(end.x),Math.floor(end.y)),q=[a],prev=new Map([[K(a.x,a.y),null]]);while(q.length){const c=q.shift();if(c.x===b.x&&c.y===b.y)break;neigh(w,c.x,c.y).forEach(n=>{const k=K(n.x,n.y);if(!prev.has(k)){prev.set(k,c);q.push(n);}});}if(!prev.has(K(b.x,b.y)))return[];const out=[];let c=b;while(c&&!(c.x===a.x&&c.y===a.y)){out.unshift({x:c.x+.5,y:c.y+.5});c=prev.get(K(c.x,c.y));}return out;}
function reveal(w,x,y,rad){const a=Math.floor(x),b=Math.floor(y);for(let yy=b-rad;yy<=b+rad;yy++)for(let xx=a-rad;xx<=a+rad;xx++)if(inside(xx,yy)&&Math.hypot(xx-a,yy-b)<=rad+.4)w.discovered.add(K(xx,yy));}
function score(p){const n=state.map[p.roomId];if(!n||p.searched||n.cleared||n.type==='base')return-Infinity;return tilePriority(n)+(n.type==='boss'&&currentPlan().focus!=='boss'?-8:0);}
function target(w){const a=w.props.filter(p=>score(p)>-Infinity);a.sort((x,y)=>score(y)-score(x)||dist(w.dog,x)-dist(w.dog,y));return a[0]||null;}
function setTarget(w,p){if(!p)return;w.dog.targetProp=p.id;w.dog.path=path(w,w.dog,p);}
function sync(w){let hit=state.map[0],best=Infinity;state.map.forEach(n=>{const c=w.rooms[n.id];if(!c)return;const d=Math.hypot(w.dog.x-c.cx-.5,w.dog.y-c.cy-.5);if(d<best){best=d;hit=n;}});if(hit)state.position={x:hit.x,y:hit.y};}
function search(w){const p=w.props.find(x=>!x.searched&&dist(w.dog,x)<.85);if(!p)return false;const n=state.map[p.roomId];p.searched=true;w.searched++;w.dog.path=[];w.dog.targetProp=null;if(n){state.position={x:n.x,y:n.y};revealAround(n.x,n.y,state.dog.scoutRange);resolveTile(n);p.type=n.type;}return true;}
function spawn(){const w=W();if(!w.ready)return;const r=rng(w.seed+'-enemies'),count=3+state.zoneId+(state.modifier?.enemyBoost?2:0)+(currentPlan().roamers||0);w.enemies=[];state.roamEnemies=[];for(let n=0;n<count;n++){const t=pick(currentZone().enemies),p=randomFloor(w,r,w.dog),hp=Math.round(t.hp*(state.weather?.enemy||1)*currentPlan().enemy),e={id:'world-enemy-'+n,template:t,sprite:t.sprite,name:t.name,x:p.x+.5,y:p.y+.5,path:[],hp,maxHp:hp,active:true,facing:-1,think:r()*2};w.enemies.push(e);state.roamEnemies.push({id:e.id,template:t,sprite:e.sprite,name:e.name,hp,maxHp:hp,active:true,left:0,top:0});}}
function dog(w,dt){if(!state.running||state.mode!=='roaming')return;if(!w.dog.path.length){if(search(w))return;setTarget(w,target(w));if(!w.dog.path.length&&!w.dog.targetProp&&!target(w))endRaid(true);}const n=w.dog.path[0];if(!n)return;const dx=n.x-w.dog.x,dy=n.y-w.dog.y,d=Math.hypot(dx,dy),sp=1.55+state.dog.speed*.24;w.dog.facing=dx<0?-1:dx>0?1:w.dog.facing;if(d<sp*dt){w.dog.x=n.x;w.dog.y=n.y;w.dog.path.shift();reveal(w,w.dog.x,w.dog.y,4+Math.min(2,state.dog.scoutRange));sync(w);search(w);}else{w.dog.x+=dx/d*sp*dt;w.dog.y+=dy/d*sp*dt;}}
function foes(w,dt){if(!state.running||state.mode!=='roaming')return;w.enemies.forEach(e=>{if(!e.active)return;const src=state.roamEnemies.find(x=>x.id===e.id);if(src&&src.active===false){e.active=false;return;}e.think-=dt;const dd=dist(e,w.dog);if(e.think<=0||!e.path.length){const chase=dd<6.5||e.template.behavior==='chaser',dest=chase?w.dog:randomFloor(w,Math.random,e);e.path=path(w,e,dest);e.think=chase?.45:1.5+Math.random()*2;}const n=e.path[0];if(n){const dx=n.x-e.x,dy=n.y-e.y,d=Math.hypot(dx,dy),sp=e.template.behavior==='chaser'?1.45:1.05;e.facing=dx<0?-1:dx>0?1:e.facing;if(d<sp*dt){e.x=n.x;e.y=n.y;e.path.shift();}else{e.x+=dx/d*sp*dt;e.y+=dy/d*sp*dt;}}if(dist(e,w.dog)<.9)startCombat(e.template,false,e.id);});}
function canvas(){const m=$('map');if(!m)return null;let c=m.querySelector('#raidWorldCanvas');if(!c){m.innerHTML='';c=document.createElement('canvas');c.id='raidWorldCanvas';c.width=VW*T;c.height=VH*T;c.setAttribute('aria-label','Top-down dungeon raid world');m.appendChild(c);const o=document.createElement('div');o.className='world-overlay';o.innerHTML='<span class="world-mode">AUTO SCAVENGE</span><span class="world-progress"></span>';m.appendChild(o);}return c;}
function tile(ctx,w,p,x,y){const px=x*T,py=y*T;if(w.tiles[y][x]){ctx.fillStyle=(x+y)%2?p.a:p.b;ctx.fillRect(px,py,T,T);ctx.strokeStyle=p.l;ctx.globalAlpha=.16;ctx.strokeRect(px+.5,py+.5,T-1,T-1);ctx.globalAlpha=1;}else{ctx.fillStyle=p.w;ctx.fillRect(px,py,T,T);if((x*13+y*7)%11===0){ctx.fillStyle='rgba(255,255,255,.025)';ctx.fillRect(px+4,py+5,T-8,4);}}}
function prop(ctx,w,p,time){if(p.searched)return;const n=state.map[p.roomId];if(!n||n.type==='empty')return;const im=img(AS[n.type]||AS.empty),bob=Math.sin(time*2.2+p.pulse)*2,size=n.type==='boss'?48:n.type==='base'?42:34,x=p.x*T-size/2,y=p.y*T-size/2+bob;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(p.x*T,p.y*T+14,size*.34,6,0,0,Math.PI*2);ctx.fill();if(im.complete)ctx.drawImage(im,x,y,size,size);if(dist(w.dog,p)<2.2){ctx.strokeStyle='#ffd970';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x*T,p.y*T,22+Math.sin(time*4)*2,0,Math.PI*2);ctx.stroke();}}
function actor(ctx,a,src,size,face,time,on=true){if(!on)return;const im=img(src),x=a.x*T,y=a.y*T;ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(x,y+size*.28,size*.28,6,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(x,y-Math.sin(time*7)*1.5);ctx.scale(face,1);if(im.complete)ctx.drawImage(im,-size/2,-size*.72,size,size);ctx.restore();}
function fog(ctx,w,p){ctx.fillStyle=p.f;ctx.globalAlpha=.94;for(let y=0;y<WH;y++)for(let x=0;x<WW;x++)if(!w.discovered.has(K(x,y)))ctx.fillRect(x*T,y*T,T+1,T+1);ctx.globalAlpha=1;}
function draw(now=performance.now()){const w=W(),c=canvas();if(!c||!w.ready)return;const ctx=c.getContext('2d'),p=PAL[biomeKey()]||PAL.city,tx=clamp(w.dog.x-VW/2,0,WW-VW),ty=clamp(w.dog.y-VH/2,0,WH-VH);w.camera.x+=(tx-w.camera.x)*.08;w.camera.y+=(ty-w.camera.y)*.08;ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.translate(-w.camera.x*T,-w.camera.y*T);for(let y=0;y<WH;y++)for(let x=0;x<WW;x++)tile(ctx,w,p,x,y);w.props.forEach(x=>prop(ctx,w,x,now/1000));w.enemies.forEach(e=>actor(ctx,e,e.sprite,42,e.facing,now/1000,e.active));actor(ctx,w.dog,state.dog.sprite,48,w.dog.facing,now/1000);fog(ctx,w,p);const ce=w.enemies.find(e=>e.id===state.combat?.enemy?.sourceId);if(ce){ctx.strokeStyle='#e96c60';ctx.lineWidth=3;ctx.beginPath();ctx.arc(ce.x*T,ce.y*T,24,0,Math.PI*2);ctx.stroke();}ctx.restore();const o=$('map')?.querySelector('.world-progress');if(o)o.textContent=`${w.searched}/${w.props.filter(p=>state.map[p.roomId]?.type!=='base').length} searched · ${w.enemies.filter(e=>e.active).length} hostiles`;}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;const w=W();if(w.ready){dog(w,dt);foes(w,dt);draw(now);}raf=requestAnimationFrame(loop);}
generateMap=function(seed){oldGen(seed);build();};generateRoamingEnemies=spawn;updateRoamingEnemies=function(){};moveDog=function(){const w=W();if(!w.ready)return oldMove();if(!w.dog.path.length)setTarget(w,target(w));};renderMap=function(){canvas();draw();};
window.worldV27={rebuild:()=>{build();spawn();render();},findPath:(a,b)=>path(W(),a,b),state:()=>W()};if(state.map?.length)build();const h=$('map')?.closest('.map-panel')?.querySelector('h2');if(h)h.textContent='Raid World';cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);render();
})();
